<?php

namespace Works\CommonBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * JobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRepository extends EntityRepository
{
    /**
     * Get current user jobs list
     */
    public function getUserList($userId)
    {
        
        $qb = $this->createQueryBuilder('j')
                ->where('j.user_id = :userId')
                ->setParameter('userId', $userId)
                ->orderBy('j.created_at');
                
        return $qb->getQuery()->getResult();
    }
    
    /**
     * Get job by PK-key.
     */
    public function getByPk($id)
    {
        $qb = $this->createQueryBuilder('j')
                ->select(array('j', 'u'))
                ->where('j.id = :id')
                ->leftJoin('j.user', 'u')
                ->setParameter('id', $id);
                
        return $qb->getQuery()->getOneOrNullResult();
    }
    
    /**
     * Get last records.
     */
    public function getLast()
    {
        $qb = $this->createQueryBuilder('j')
                ->select(array('j', 'u'))
                ->leftJoin('j.user', 'u')
                ->orderBy('j.type DESC, j.created_at', 'DESC');
                
        return $qb->getQuery()->getResult();
    }
}
